"""add context changes

Revision ID: be40c44aea52
Revises: 83c2ddbab36b
Create Date: 2026-08-09 16:23:29.262170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be40c44aea52"
down_revision: Union[str, Sequence[str], None] = "83c2ddbab36b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context_changes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("context_id", sa.String(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_changes_context_id"),
        "context_changes",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_changes_user_id"), "context_changes", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_context_changes_user_id"), table_name="context_changes")
    op.drop_index(op.f("ix_context_changes_context_id"), table_name="context_changes")
    op.drop_table("context_changes")
    # ### end Alembic commands ###
