MAX_CONTEXT_ITEMS = 20
MAX_MEMORY_RESULTS = 15
MAX_REFLECTIONS = 5
DEFAULT_EMBEDDING_DIMENSION = 1024

__all__ = [
    "DEFAULT_EMBEDDING_DIMENSION",
    "MAX_CONTEXT_ITEMS",
    "MAX_MEMORY_RESULTS",
    "MAX_REFLECTIONS",
]
