DEFAULT_SPACE_COLOR = "#3B82F6"
DEFAULT_SPACE_ICON = "folder"
DEFAULT_PRIORITY = 3
DEFAULT_PROGRESS = 0

__all__ = [
    "DEFAULT_PRIORITY",
    "DEFAULT_PROGRESS",
    "DEFAULT_SPACE_COLOR",
    "DEFAULT_SPACE_ICON",
]
