AUTO_ACTION_THRESHOLD = 90
SUGGESTION_THRESHOLD = 70
QUESTION_THRESHOLD = 50
MEMORY_IMPORTANCE_THRESHOLD = 75
HABIT_CONFIDENCE_THRESHOLD = 80

__all__ = [
    "AUTO_ACTION_THRESHOLD",
    "HABIT_CONFIDENCE_THRESHOLD",
    "MEMORY_IMPORTANCE_THRESHOLD",
    "QUESTION_THRESHOLD",
    "SUGGESTION_THRESHOLD",
]
