"""add reminder processing metadata

Revision ID: 23bcf2bec4c9
Revises: 27b5ee51d240
Create Date: 2026-08-18 22:52:34.445033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bcf2bec4c9'
down_revision: Union[str, Sequence[str], None] = '27b5ee51d240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reminders', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'last_error')
    op.drop_column('reminders', 'processed_at')
    # ### end Alembic commands ###
