"""add reminder retry fields

Revision ID: 3a57155ec184
Revises: 23bcf2bec4c9
Create Date: 2026-08-18 23:48:55.344147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a57155ec184'
down_revision: Union[str, Sequence[str], None] = '23bcf2bec4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "reminders",
        sa.Column(
            "attempt_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "reminders",
        sa.Column(
            "last_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "reminders",
        sa.Column(
            "processing_started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'processing_started_at')
    op.drop_column('reminders', 'last_attempt_at')
    op.drop_column('reminders', 'attempt_count')
    # ### end Alembic commands ###
