"""add reminder duplicate constraint

Revision ID: 4a5653932066
Revises: 3a57155ec184
Create Date: 2026-08-19 18:21:41.285266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5653932066'
down_revision: Union[str, Sequence[str], None] = '3a57155ec184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reminder_owner_title_schedule_recurrence', 'reminders', ['owner_id', 'title', 'scheduled_for', 'recurrence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reminder_owner_title_schedule_recurrence', 'reminders', type_='unique')
    # ### end Alembic commands ###
