"""add timezone to reminders

Revision ID: 815a4ddbeda7
Revises: 4a5653932066
Create Date: 2026-08-21 14:55:06.147717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815a4ddbeda7'
down_revision: Union[str, Sequence[str], None] = '4a5653932066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "reminders",
        sa.Column(
            "timezone",
            sa.String(length=100),
            nullable=False,
            server_default="Asia/Kolkata",
        ),
    )

    op.alter_column(
        "reminders",
        "timezone",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'timezone')
    # ### end Alembic commands ###
