"""add cascade delete to project members

Revision ID: 651ac732bdf0
Revises: f5bb7ca8e309
Create Date: 2026-08-06 10:51:07.563555

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "651ac732bdf0"
down_revision: str | Sequence[str] | None = "f5bb7ca8e309"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("project_members_project_id_fkey"), "project_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_members", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_members_project_id_fkey"),
        "project_members",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
