"""add project activity state

Revision ID: b67718d97b63
Revises: 651ac732bdf0
Create Date: 2026-08-10 16:52:21.917286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67718d97b63'
down_revision: Union[str, Sequence[str], None] = '651ac732bdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('current_focus', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('latest_activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'latest_activity')
    op.drop_column('projects', 'current_focus')
    # ### end Alembic commands ###
