"""add space project associations

Revision ID: 3a4fbf48dbe7
Revises: 478eec8ec757
Create Date: 2026-08-10 14:18:58.702330

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a4fbf48dbe7'
down_revision: str | Sequence[str] | None = '478eec8ec757'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('space_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'project_id', name='uq_space_project')
    )
    op.create_index(op.f('ix_space_projects_project_id'), 'space_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_space_projects_space_id'), 'space_projects', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_projects_space_id'), table_name='space_projects')
    op.drop_index(op.f('ix_space_projects_project_id'), table_name='space_projects')
    op.drop_table('space_projects')
    # ### end Alembic commands ###
